### ISSUE TITLE
RUN的时候出现：没有item_embeddings.npy&user_embeddings.npy文件

### ISSUE THREAD

**Issue by SceneRec** [THUDM/ScenarioMeta#2]
Thanks for your great work！在main.py文件中265行有item_embeddings.npy，在作者提供的数据集中，没有main.py中所需要的.npy文件，请问这些文件在哪里获取？ 新手需要您的指导！
期待您的回复！

**Comment by duzx16** [comment]
您好，在提供的预处理的数据集中包含了需要的.npy文件。
